### ISSUE TITLE
iOS Memory Leak Issue

### ISSUE THREAD

**Issue by NilayDag** [Kotlin/kotlinx.atomicfu#196]
### **New Issue Checklist**
- [x]  I searched for existing GitHub issues

**Info**

I'm using:
```
kotlin: 1.5.20
ktor: 1.6.0
kotlinx-coroutines: 1.4.3-native-mt
```
for a Kotlin Multiplatform project.

### **Describe the bug**
kotlinx-atomicfu creates memory leak in our iOS part of the project. Here is the place of the leak:

```
>  atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/AtomicFU.kt:17
```

And ss for the last line of the memory leak's stack trace in case you need:

<img width="686" alt="Kotlinx AtomicFu Memory Leak" src="https://user-images.githubusercontent.com/20637243/129031264-e6f035c8-9f27-4d97-b544-89e4977477d5.png">

**### Expected behavior**
kotlinx-atomicfu shouldn't create any memory leaks in iOS.

**Comment by mvicsokolova** [comment]
I guess, this issue was caused by the Kotlin Native memory management. 

You can check out the new experimental memory manager for Kotlin Native: https://blog.jetbrains.com/kotlin/2021/08/try-the-new-kotlin-native-memory-manager-development-preview/. And also consider [the new memory model migration guide](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md).
